"""add_table_weather_data

Revision ID: 7bdb334ac6f7
Revises: 
Create Date: 2022-02-19 23:51:55.849670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdb334ac6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('city', sa.VARCHAR(length=32), nullable=False),
    sa.Column('country', sa.VARCHAR(length=32), nullable=False),
    sa.Column('datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('main', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.VARCHAR(length=32), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('wind_speed', sa.FLOAT(), nullable=False),
    sa.Column('wind_dir', sa.SMALLINT(), nullable=False),
    sa.Column('humidity', sa.SMALLINT(), nullable=False),
    sa.Column('rain_1h', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('rain_3h', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('clouds', sa.SMALLINT(), nullable=False),
    sa.Column('visibility', sa.INTEGER(), nullable=False),
    sa.Column('timezone', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('city', 'country', 'datetime', name=op.f('pk_weather_data'))
    )

    # Manually-added check constraints.
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.column("wind_speed") >= 0,
    )
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.and_(sa.column("wind_dir") >= 0, sa.column("wind_dir") <= 360),
    )
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.and_(sa.column("humidity") >= 0, sa.column("humidity") <= 100),
    )
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.column("rain_1h") >= 0,
    )
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.column("rain_3h") >= 0,
    )
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.and_(sa.column("clouds") >= 0, sa.column("clouds") <= 100),
    )
    op.create_check_constraint(
        constraint_name=None,
        table_name='weather_data',
        condition=sa.column("visibility") >= 0,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    # ### end Alembic commands ###
